frontegg:
  clientId: 0677451a-bddc-4e9a-8c84-d98b220e1881
  apiKey: f940981e-acf6-42a0-bca4-39d9f732a516
  config:
    urls:
      baseUrl: https://api.frontegg.com
      authenticationService: /vendors/auth/token
      auditsService: /audits/
      notificationService: /notification/
      tenantsService: /tenants/
      metadataService: /metadata/
      teamService: /team
      eventService: /event
      identityService: /identity
  whitelist:
    - /metadata