name: Frontegg Java SDK CI

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.adoc"
      - "*.txt"
      - ".github/ISSUE_TEMPLATE/**"
env:
  LANG: en_US.UTF-8
jobs:
  build-and-cache-deps:
    name: Build JDK 17
    runs-on: ubuntu-latest
    if: github.repository == 'frontegg/java-sdk'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build
        run: |
          mvn -e -B -DskipTests -DskipITs -Dno-format clean package
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-and-cache-deps
    if: github.repository == 'frontegg/java-sdk'
    strategy:
      fail-fast: false
      matrix:
        java:
          - name: "17"
            java-version: 17
          - name: "21"
            java-version: 21
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java.java-version }}
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Test
        run: |
          mvn -e -B test