name: Frontegg Java SDK CI

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.adoc"
      - "*.txt"
      - ".github/ISSUE_TEMPLATE/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - ".github/ISSUE_TEMPLATE/**"
env:
  LANG: en_US.UTF-8
  JVM_TEST_MAVEN_OPTS: "-e -B --settings .github/mvn-settings.xml"
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    if: github.repository == 'frontegg/java-sdk'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Date for cache
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          mvn -e -B -DskipTests -DskipITs -Dno-format clean install
