name: Frontegg Java SDK CI

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.adoc"
      - "*.txt"
      - ".github/ISSUE_TEMPLATE/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - ".github/ISSUE_TEMPLATE/**"
env:
  LANG: en_US.UTF-8
  JVM_TEST_MAVEN_OPTS: "-e -B --settings .github/mvn-settings.xml"
jobs:
  build-and-cache-deps:
    name: Build JDK 8
    runs-on: ubuntu-latest
    if: github.repository == 'frontegg/java-sdk'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build
        run: |
          mvn -e -B -DskipTests -DskipITs -Dno-format clean package
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-and-cache-deps
    if: github.repository == 'frontegg/java-sdk'
    strategy:
      fail-fast: false
      matrix:
        java:
          - name: "8"
            java-version: 8
          - name: "11"
            java-version: 11
          - name: "15"
            java-version: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java.java-version }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Test
        run: |
          mvn -e -B test