name: Frontegg Java SDK - release

on:
  push:
    branches:
      - "main"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  actions: read
  checks: write
  contents: write

env:
  LANG: en_US.UTF-8
jobs:
  release:
    name: Release the new version
    runs-on: ubuntu-latest
    if: |
      github.repository == 'frontegg/java-sdk' &&
      startsWith(github.event.head_commit.message, '[maven-release-plugin] prepare release')
    steps:
      - id: create_bot_token
        name: Create bot token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.GH_FRONTEGG_BOT_APP_ID }}
          private_key: ${{ secrets.GH_FRONTEGG_BOT_APP_SECRET }}
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.create_bot_token.outputs.BOT_TOKEN }}
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: ossrh
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -e -B clean install
      - name: Release
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -e -B -Prelease deploy
