name: Frontegg Java SDK - create release

on:
  push:
    branches:
      - "*"
env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: Build JDK 8
    runs-on: ubuntu-latest
    if: github.repository == 'frontegg/java-sdk'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -e -B --settings .github/mvn-settings.xml clean install
      - name: Import gpg
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
      - name: Preapare release
        run: mvn -e -B -Prelease release:prepare -DdryRun=true